const express=require('express')
const app=express()
const dotenv=require('dotenv')
const mongoose=require('mongoose')
const CategoryRoute=require('./routes/categoryroute')
const RestaurantRoute=require('./routes/restaurantroute')
const FoodRoute=require('./routes/foodRoute')
const RatingRoute=require('./routes/ratingRoute')
const AuthRoute=require('./routes/authroute')
const UserRoute=require("./routes/userroute")
const AddressRoute=require("./routes/addressroute")
const CartRoute=require('./routes/cartRoute')
const OrderRoute=require('./routes/orderRoute')
dotenv.config()
mongoose.connect(process.env.DB).then(()=>console.log('connected to database')).catch((err)=>console.log(err))

app.use(express.json())
app.use(express.urlencoded({extended:true}))
app.use('/api',AuthRoute)
app.use('/api/user',UserRoute)
app.use("/api/category",CategoryRoute)
app.use("/api/restaurant",RestaurantRoute)
app.use("/api/foods",FoodRoute)
app.use('api/rating',RatingRoute)
app.use('/api/address',AddressRoute)
app.use('/api/cart',CartRoute)
app.use('/api/order',OrderRoute)
app.listen(process.env.PORT||6013,console.log(`app running on port ${process.env.PORT}`))