const express=require('express')
const app=express()
const dotenv=require('dotenv')
const mongoose=require('mongoose')
const CategoryRoute=require('./routes/categoryroute')
const RestaurantRoute=require('./routes/restaurantroute')
const FoodRoute=require('./routes/foodRoute')
const RatingRoute=require('./routes/ratingRoute')

dotenv.config()
mongoose.connect(process.env.DB).then(()=>console.log('connected to database')).catch((err)=>console.log(err))

app.use(express.json())
app.use(express.urlencoded({extended:true}))
app.use("/api/category",CategoryRoute)
app.use("/api/restaurant",RestaurantRoute)
app.use("/api/foods",FoodRoute)
app.use('api/rating',RatingRoute)
app.listen(process.env.PORT||6013,console.log(`app running on port ${process.env.PORT}`))